spring:

  datasource:
    url: jdbc:mysql://localhost:3306/weakpoint?serverTimezone=Asia/Seoul
    username: root
    password: "004637"
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: ${redis.host}
      port: ${redis.port}

