spring:

  datasource:
    url: jdbc:mysql://localhost:3306/weakpoint?serverTimezone=Asia/Seoul
    username: root
    password: "004637"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

